### ISSUE TITLE
Develop: Edit Post Type feature

### ISSUE THREAD

**Issue by OrkanMetin** [OrkanMe/SWE-573#25]
The Post Type must be editable to the user, who created the Post Type. The user shall be able to delete or add fields, or edit the name of the field and/or type in the related post type. While the recent Post Type is edited, the remaining posts continue to be published in their previous format, through the previous field types and names.

**Comment by uskudarli** [comment]
I see you are busy busy... )

What is edit post type? Since there is no description it is difficult to grasp.

Do you mean, 

The post type must be editable to delete or add fields, or edit the name of the field and/or type?

Also, a note that such edits will impact the implementation related to viewing posts created with earlier versions of the post type. I link to such tasks and/or design ciould be useful.

**Comment by OrkanMetin** [comment]
Suzan Hocam,

Teşekkürler yorumlarınız için, çok hastaydım, akşam issue create edip
çıkmak zorunda kaldım ofisten, eve arkadaşım bıraktı. Halen iyi değilim.
İlk fırsatta gerekli düzenlemeleri yaparak devam edeceğim.

Saygılarımla.
Orkan Metin

13 Ara 2019 Cum, saat 21:41 tarihinde uskudarli <notifications@github.com>
şunu yazdı:

**Comment by OrkanMetin** [comment]
The post type feature is implemented successfully. Title, body, semantic tag and any type of new field is able to be added. (Location and Enum is not completed.) The new record is able to be seen in the DB. However, in this phase, editing the post type feature could not been accomplished.

**TO DO:** Complete using the data type for creating new post.
